version: 2
updates:
  - package-ecosystem: gomod
    directory: /apps/backend
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /apps/frontend
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5
    groups:
      svelte:
        patterns:
          - "svelte*"
          - "@sveltejs/*"

  - package-ecosystem: npm
    directory: /packages/api-schema
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 3

  - package-ecosystem: pip
    directory: /apps/pyworkers
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: docker
    directory: /apps/backend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/frontend
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/pyworkers
    schedule:
      interval: weekly
