-- Generated by scripts/build-sqlc-schema.py from infra/migrations/.
-- DO NOT EDIT — run `make sqlc-schema` to regenerate.
--
-- Diese Datei ist ausschließlich Input für sqlc. Source-of-Truth für das
-- Live-DB-Schema bleibt infra/migrations/, gepflegt über goose.

-- ------------------------------------------------------------
-- From: infra/migrations/0001_open_meteo_hello_world.sql
-- ------------------------------------------------------------


CREATE TABLE locations (
    id          BIGSERIAL PRIMARY KEY,
    slug        TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    country     TEXT NOT NULL DEFAULT 'DE',
    latitude    DOUBLE PRECISION NOT NULL,
    longitude   DOUBLE PRECISION NOT NULL,
    timezone    TEXT NOT NULL DEFAULT 'Europe/Berlin',
    source      TEXT NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE observations (
    location_id    BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    observed_at    TIMESTAMPTZ NOT NULL,
    temperature    DOUBLE PRECISION,
    precipitation  DOUBLE PRECISION,
    wind_speed     DOUBLE PRECISION,
    wind_direction INTEGER,
    source         TEXT NOT NULL,
    fetched_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (location_id, observed_at)
);

CREATE INDEX idx_observations_location_observed
    ON observations (location_id, observed_at DESC);

CREATE TABLE forecasts (
    location_id    BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    forecast_for   TIMESTAMPTZ NOT NULL,
    run_at         TIMESTAMPTZ NOT NULL,
    temperature    DOUBLE PRECISION,
    precipitation  DOUBLE PRECISION,
    wind_speed     DOUBLE PRECISION,
    wind_direction INTEGER,
    source         TEXT NOT NULL,
    fetched_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (location_id, forecast_for, run_at)
);

CREATE INDEX idx_forecasts_location_forecast_for
    ON forecasts (location_id, forecast_for DESC);

-- ------------------------------------------------------------
-- From: infra/migrations/0002_dwd_poi_stations_and_variables.sql
-- ------------------------------------------------------------


-- Erweitere observations-PK um source, damit DWD und Open-Meteo parallel
-- für dieselbe (location_id, observed_at) speichern können, ohne sich zu
-- überschreiben. observed_at bleibt drin, deshalb akzeptiert TimescaleDB
-- die neue PK auf der Hypertable.
ALTER TABLE observations DROP CONSTRAINT observations_pkey;
ALTER TABLE observations ADD PRIMARY KEY (location_id, source, observed_at);

-- locations: dwd_station_id (Schlüssel für POI-CSV-Fetch) + altitude_m
-- (Frontend zeigt Höhe für Klimakontrast-Stationen).
ALTER TABLE locations
    ADD COLUMN dwd_station_id TEXT,
    ADD COLUMN altitude_m     INTEGER;

CREATE INDEX idx_locations_dwd_station_id
    ON locations (dwd_station_id)
    WHERE dwd_station_id IS NOT NULL;

-- observations: pressure (hPa MSL) + humidity (% relative).
ALTER TABLE observations
    ADD COLUMN pressure DOUBLE PRECISION,
    ADD COLUMN humidity DOUBLE PRECISION;
