#!/usr/bin/env python3
"""
Generiert apps/backend/internal/storage/schema.sql aus den goose-Migrations
in infra/migrations/.

Hintergrund: sqlc liest DDL aus einer Schema-Datei oder einem Verzeichnis und
parst sie linear. Würde es unsere Migrations direkt lesen, sähe es zuerst
die CREATE-TABLE-Statements im '-- +goose Up'-Block und danach die
DROP-TABLE-Statements im '-- +goose Down'-Block — Ergebnis: leeres Schema.

Dieses Skript löst das Problem, indem es:

  1. Alle infra/migrations/*.sql in alphabetischer Reihenfolge liest.
  2. Aus jeder Datei nur den '-- +goose Up'-Abschnitt extrahiert.
  3. Statements verwirft, die für sqlc irrelevant sind (INSERT/DELETE und
     TimescaleDB-spezifische create_hypertable()-Aufrufe).
  4. Den Rest zu einer schema.sql konkateniert.

Wird via `make sqlc-schema` aufgerufen. Output-Datei ist committed; CI
prüft via `make gen-check`, dass sie aktuell ist.

Live-DB-Schema bleibt durch goose gegen infra/migrations/ gepflegt —
schema.sql ist *nur* der Input für sqlc.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MIGRATIONS_DIR = REPO_ROOT / "infra" / "migrations"
OUTPUT_FILE = REPO_ROOT / "apps" / "backend" / "internal" / "storage" / "schema.sql"

HEADER = """\
-- Generated by scripts/build-sqlc-schema.py from infra/migrations/.
-- DO NOT EDIT — run `make sqlc-schema` to regenerate.
--
-- Diese Datei ist ausschließlich Input für sqlc. Source-of-Truth für das
-- Live-DB-Schema bleibt infra/migrations/, gepflegt über goose.

"""


def extract_up_section(content: str) -> str:
    """Alles zwischen '-- +goose Up' und '-- +goose Down' zurückgeben."""
    in_up = False
    out: list[str] = []
    for line in content.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("-- +goose Up"):
            in_up = True
            continue
        if stripped.startswith("-- +goose Down"):
            in_up = False
            continue
        if in_up:
            out.append(line)
    return "".join(out)


def split_statements(content: str) -> list[str]:
    """In Einzel-Statements zerlegen (Trenner: ';' am Zeilenende).

    Respektiert '-- +goose StatementBegin/StatementEnd' für Blöcke mit
    eingebetteten Semikolons (z. B. PL/pgSQL-Funktionskörper).
    """
    statements: list[str] = []
    buf: list[str] = []
    in_block = False
    for line in content.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("-- +goose StatementBegin"):
            in_block = True
            continue
        if stripped.startswith("-- +goose StatementEnd"):
            in_block = False
            if buf:
                statements.append("".join(buf))
                buf = []
            continue
        buf.append(line)
        if not in_block and stripped.endswith(";"):
            statements.append("".join(buf))
            buf = []
    leftover = "".join(buf).strip()
    if leftover:
        statements.append("".join(buf))
    return statements


def is_skippable(stmt: str) -> bool:
    """True, wenn das Statement für sqlc irrelevant ist."""
    for line in stmt.splitlines():
        s = line.strip()
        if not s or s.startswith("--"):
            continue
        up = s.upper()
        if up.startswith("INSERT"):
            return True
        if up.startswith("UPDATE"):
            return True
        if up.startswith("DELETE"):
            return True
        if up.startswith("SELECT CREATE_HYPERTABLE"):
            return True
        return False
    return True


def main() -> int:
    if not MIGRATIONS_DIR.is_dir():
        print(f"Error: {MIGRATIONS_DIR} not a directory", file=sys.stderr)
        return 1

    migration_files = sorted(MIGRATIONS_DIR.glob("*.sql"))
    if not migration_files:
        print(f"Error: no .sql files in {MIGRATIONS_DIR}", file=sys.stderr)
        return 1

    parts: list[str] = [HEADER]
    for path in migration_files:
        parts.append("-- " + "-" * 60 + "\n")
        parts.append(f"-- From: {path.relative_to(REPO_ROOT)}\n")
        parts.append("-- " + "-" * 60 + "\n\n")
        up = extract_up_section(path.read_text())
        for stmt in split_statements(up):
            if is_skippable(stmt):
                continue
            parts.append(stmt)
            if not stmt.endswith("\n"):
                parts.append("\n")
        parts.append("\n")

    output = "".join(parts).rstrip() + "\n"
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output)
    print(f"Wrote {OUTPUT_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
