// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for GetLocationDetailParamsSource.
const (
	Dwd       GetLocationDetailParamsSource = "dwd"
	OpenMeteo GetLocationDetailParamsSource = "open-meteo"
)

// ForecastEntry Ein stündlicher Vorhersage-Datenpunkt.
type ForecastEntry struct {
	ForecastFor   time.Time `json:"forecastFor"`
	Precipitation *float32  `json:"precipitation,omitempty"`

	// RunAt Zeitpunkt des Forecast-Runs (alle Einträge eines Calls teilen dasselbe runAt).
	RunAt         time.Time `json:"runAt"`
	Temperature   *float32  `json:"temperature,omitempty"`
	WindDirection *int      `json:"windDirection,omitempty"`
	WindSpeed     *float32  `json:"windSpeed,omitempty"`
}

// Location defines model for Location.
type Location struct {
	// AltitudeM Stations-Höhe über Normalnull in Metern (falls bekannt).
	AltitudeM *int `json:"altitudeM,omitempty"`

	// AvailableSources Liste aller Datenquellen, für die diese Location aktuell
	// Observations in der DB hat (z.B. `["dwd", "open-meteo"]`).
	// Leeres Array, wenn noch nichts geschrieben wurde.
	AvailableSources *[]string `json:"availableSources,omitempty"`

	// Country ISO 3166-1 alpha-2
	Country string `json:"country"`

	// DwdStationId WMO-Synop-Kennung der DWD-Station für diese Location, falls eine
	// verknüpft ist. Wird zum Abruf aus opendata.dwd.de/.../poi/ benutzt.
	DwdStationId *string `json:"dwdStationId,omitempty"`
	Id           int64   `json:"id"`
	Latitude     float64 `json:"latitude"`
	Longitude    float64 `json:"longitude"`
	Name         string  `json:"name"`

	// Slug URL-safe key, z.B. "potsdam"
	Slug string `json:"slug"`

	// Source Default-Datenquelle (Legacy-Feld aus 2.1; nutze `availableSources`).
	Source string `json:"source"`

	// Timezone IANA timezone, z.B. Europe/Berlin
	Timezone string `json:"timezone"`
}

// LocationDetail defines model for LocationDetail.
type LocationDetail struct {
	Attribution string `json:"attribution"`

	// Current Eine Messung (current oder historisch).
	Current *Observation `json:"current,omitempty"`

	// Forecast Stündliche Forecast-Einträge für die nächsten 24 h (kann leer sein).
	Forecast []ForecastEntry `json:"forecast"`
	Location Location        `json:"location"`
}

// Observation Eine Messung (current oder historisch).
type Observation struct {
	FetchedAt time.Time `json:"fetchedAt"`

	// Humidity Relative Luftfeuchte in %. Fehlt, wenn Quelle null liefert.
	Humidity   *float32  `json:"humidity,omitempty"`
	ObservedAt time.Time `json:"observedAt"`

	// Precipitation Niederschlag in mm. Fehlt, wenn Quelle null liefert.
	Precipitation *float32 `json:"precipitation,omitempty"`

	// Pressure Luftdruck in hPa, auf Meereshöhe reduziert (MSL). Fehlt, wenn
	// Quelle null liefert (z.B. DWD-Hochgebirgsstationen >2000 m).
	Pressure *float32 `json:"pressure,omitempty"`
	Source   string   `json:"source"`

	// Temperature Temperatur in °C (2 m über Grund). Fehlt, wenn Quelle null liefert.
	Temperature *float32 `json:"temperature,omitempty"`

	// WindDirection Windrichtung in Grad (0 = N, 90 = O). Fehlt, wenn Quelle null liefert.
	WindDirection *int `json:"windDirection,omitempty"`

	// WindSpeed Windgeschwindigkeit in km/h (10 m über Grund). Fehlt, wenn Quelle null liefert.
	WindSpeed *float32 `json:"windSpeed,omitempty"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	Message string `json:"message"`
	TraceId string `json:"traceId"`
}

// Problem Problem details object as per RFC 7807.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  *string `json:"traceId,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// NotFound Problem details object as per RFC 7807.
type NotFound = Problem

// GetLocationDetailParams defines parameters for GetLocationDetail.
type GetLocationDetailParams struct {
	// Source Wählt die Datenquelle für `current` und `forecast`. Default-Logik
	// wenn nicht gesetzt: `dwd` falls die Location eine DWD-Station hat,
	// sonst `open-meteo`. Quellen, für die keine Daten in der DB liegen,
	// liefern `current = null` bzw. leeres `forecast`-Array.
	Source *GetLocationDetailParamsSource `form:"source,omitempty" json:"source,omitempty"`
}

// GetLocationDetailParamsSource defines parameters for GetLocationDetail.
type GetLocationDetailParamsSource string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all active locations
	// (GET /api/v1/locations)
	ListLocations(w http.ResponseWriter, r *http.Request)
	// Get location with latest observation and 24h-forecast
	// (GET /api/v1/locations/{slug})
	GetLocationDetail(w http.ResponseWriter, r *http.Request, slug string, params GetLocationDetailParams)
	// Connectivity check
	// (GET /api/v1/ping)
	Ping(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all active locations
// (GET /api/v1/locations)
func (_ Unimplemented) ListLocations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get location with latest observation and 24h-forecast
// (GET /api/v1/locations/{slug})
func (_ Unimplemented) GetLocationDetail(w http.ResponseWriter, r *http.Request, slug string, params GetLocationDetailParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Connectivity check
// (GET /api/v1/ping)
func (_ Unimplemented) Ping(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListLocations operation middleware
func (siw *ServerInterfaceWrapper) ListLocations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLocations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocationDetail operation middleware
func (siw *ServerInterfaceWrapper) GetLocationDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLocationDetailParams

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", r.URL.Query(), &params.Source)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocationDetail(w, r, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/locations", wrapper.ListLocations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/locations/{slug}", wrapper.GetLocationDetail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ping", wrapper.Ping)
	})

	return r
}

type NotFoundApplicationProblemPlusJSONResponse Problem

type ListLocationsRequestObject struct {
}

type ListLocationsResponseObject interface {
	VisitListLocationsResponse(w http.ResponseWriter) error
}

type ListLocations200JSONResponse struct {
	Attribution string     `json:"attribution"`
	Results     []Location `json:"results"`
}

func (response ListLocations200JSONResponse) VisitListLocationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLocationDetailRequestObject struct {
	Slug   string `json:"slug"`
	Params GetLocationDetailParams
}

type GetLocationDetailResponseObject interface {
	VisitGetLocationDetailResponse(w http.ResponseWriter) error
}

type GetLocationDetail200JSONResponse LocationDetail

func (response GetLocationDetail200JSONResponse) VisitGetLocationDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLocationDetail404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetLocationDetail404ApplicationProblemPlusJSONResponse) VisitGetLocationDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

type Ping200JSONResponse PingResponse

func (response Ping200JSONResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all active locations
	// (GET /api/v1/locations)
	ListLocations(ctx context.Context, request ListLocationsRequestObject) (ListLocationsResponseObject, error)
	// Get location with latest observation and 24h-forecast
	// (GET /api/v1/locations/{slug})
	GetLocationDetail(ctx context.Context, request GetLocationDetailRequestObject) (GetLocationDetailResponseObject, error)
	// Connectivity check
	// (GET /api/v1/ping)
	Ping(ctx context.Context, request PingRequestObject) (PingResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListLocations operation middleware
func (sh *strictHandler) ListLocations(w http.ResponseWriter, r *http.Request) {
	var request ListLocationsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLocations(ctx, request.(ListLocationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLocations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLocationsResponseObject); ok {
		if err := validResponse.VisitListLocationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLocationDetail operation middleware
func (sh *strictHandler) GetLocationDetail(w http.ResponseWriter, r *http.Request, slug string, params GetLocationDetailParams) {
	var request GetLocationDetailRequestObject

	request.Slug = slug
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLocationDetail(ctx, request.(GetLocationDetailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLocationDetail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLocationDetailResponseObject); ok {
		if err := validResponse.VisitGetLocationDetailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Ping operation middleware
func (sh *strictHandler) Ping(w http.ResponseWriter, r *http.Request) {
	var request PingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Ping(ctx, request.(PingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ping")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PingResponseObject); ok {
		if err := validResponse.VisitPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RY23LcuBH9lS5kUzWq5VwkO97VpPZBtizbFcl2JCeuikepwRA9JHZAgMZFs5JLf+MP",
	"yFOe/BT9WArgfUjZci4PKg1JoNF9+nYan0isslxJlNaQ+Sei0eRKGgwPr5U9UU4y/ztW0qK0/ifNc8Fj",
	"armS01yrlcDsx1+Nkv6biVPMqP/1g8Y1mZPfTZsDpsVXM31b7CK3t7cRYWhizXMvjszJORrldIwglYV1",
	"ON0vKnd6wSdKY0yNfS6tvvYvugKecwnG3n2RTPA4RQ1/VTpFbWiC42NqUeZObuyERCTXKkdteWHsuhR7",
	"onT5mFFL5oRRi2PLMyQRsdc5kjkxVnOZkFsvAmOec0uLwz9VK6TLVqj9Cu3kke1r+TfkNigCDA1UJo3P",
	"nTQwokIgPOfS6rvPCQJyiQaeUSEMWOQCJTBqDIoVQhC/5615mMIWsxw1tU7joLpbLtkx1xhXBmX0N565",
	"jMwfPZlFJOOyeJrVsrm0mDSbL3JENiDaQ4EfHdf+64cO2hVIl7VMtfoVY+tFnqq4xrbrLyost47hWR/c",
	"i8IfZvzy7p8pwt2XFWp47fER0gkBXMIZWtQSRuuA6go3VMoCx75Z9IpyQVcCL0Jkmv6Bp9xYBO82DSHG",
	"PjoUAmUE67svGhhH/2cQKnOAbqxfspBvVgb1VaGvV4x5EU8hpRZGN5OnE1h+WBC2ZQsSwYKoHOU4Q4tq",
	"QS6Xe5OFPEXUaOBIa3odwRalBKniFCSPU2sgQROnmuMKJWydZjhZSBIRbjEzLS+1AqR4Qb08/xwrN5xn",
	"ry7ewKP9J0/G+0BFntLxAYl8tJyiTGxK5gchWlpPvaPYlpWeesX68t+fvRlfXEuVj/+EUjqZFNC8Px6X",
	"m2psW7hGUDjUp8xCXqHeyLsv+doCN3YC77lmcOMyOFpptwbqDHhAGbV0wrZswnA6mUymueJTWKF09sYW",
	"cPVU56xTI7i0Tx4Pxo6gRZR2S4pyK4EFXEU6HbZza3zYZFeTmULJ5CGi9n/uyAqPPWGSZjjofiNc0vfF",
	"X85Px4auETZ4HUEIywXJlTWMZgviSym1Pp/InPz9Ax3fzMaH48sffxhCrqju/SOOcU2dsONW+sDoFBMa",
	"X49PULDgrYPJ/h/B+wVhuZuVy3b2tuKZZ3ij5MCJr45eH0H1ubTqufM1ZvoUteADjt8pYpyRErES0SZd",
	"Wp5vu66lTw3F18reMVrKxUDxs1bzldvpOo3VsdO67NZf68Ot4uN3VUV5qKLWDbVpVk2HqqucvPscp8ai",
	"hIPHkMLIl1UQiBoMchk8VJeerynW7fEDZUm0+sLXBNX9Y9d3tYCW2VEH1yG/tAEbYh4IZ2iML1aj0gWg",
	"fNlKubFKcxOnewPMA22cIitowsPaeOoyzrgdKMvn6APvCuHUre0aXZxa9H3l9xM4wVTYskf8uciw0A4F",
	"xzXqQImaKjIb7vZNCVEBiu9Tu0eXurq/5shQmzgVNPE6Z9mDlO6plmvvBD2Q8x4Upl288eLTtzQC6tZw",
	"FnpoGsiCRuZuOGoLo7OL072OAgs5oEHZpn1jeqniNMEV14kxhY0oYeFms0d4MJvNINvrtJNG4aYofouw",
	"dc15V3/09vzrH89gdABZSXheaCfZ3n+GYI8G7vRmLpn2BMNHOpfwQlMGoxn8Aq8jOPT/3+x9X7x9L7vs",
	"6xOYjl/Dkw1y69XaZNMURvuz/wEkO9WjFfy196JWIg/VjrdcJufleNWv6BkaP6L4n/gbzXLhN+dKJoNN",
	"TdMYX7GBgNnRs5LabBnUrBzHeriWH4CFNmSg2ALUQI4azk+ewU8/z34qgrprDqsbV587SWOpvCfcfd44",
	"0xk8/nB42AqNUJj6wWG5Ffck0L1YVXK8toF8+AazUs7OV4LKTXumcpp/kw0UKtQm9IG+DcavVTVO0ziU",
	"zoKLka3Sgm2R2hS1xK0hEXFakDlJrc3NfDrdXTCJVUZ68/PLd+/ewtHbV0VPHtozgaMwX0oWBlAEJy1q",
	"WE5pzqdX+9Nl4U/BYywjtdTw3dPjFtQ9hf2pJCJXqE2hymyyP5mFVpGjpDknc/IovAp8MQ1erg6t2nF4",
	"mWAARoXaVo4HYcY6rVdF3ZuKg9nsK5cU/cuJ72NTGo0Txf3Ig9hLQzp2ictOyFSCv0U8+tckHg1Qa6Bx",
	"aPYNfOGyxGUZ9TNbsYwK0V8XEUsT02ZChlz6zT2PTD95int7r2NeoN2hq96/mvoxVfsTPhHuVfY+r4jy",
	"vKLNDRpWO4xaLmqNkhUZqZ8fPnDcRr1ecfc5FTaw1fasEdJlWZK2JTjJYFkRw+UEqvHkVCV8s5DFnO07",
	"oJ+w0d7YOSzZli3L+dNLr2d9P4x2BteU2mghjZLGwrIZ6ZeTshm17w02xW6vaet6QHBMUEYLWXQsWWsO",
	"v4ROtoTVzXYSmDealiHjcE9Q3gF4ND46DNNK5ZWqlTV+QOnL7gc/rZOodQHRCtMa7Mv/Mi0fklRljA3l",
	"RAV40Xwg4xYqWLw/a55/G5HHs8f3HVhbMK3vP7tJ9QJtnUiw5TYFQS36fGymA6CSwcHjdNwaLvoJF5Gy",
	"fnZTL/do3pdunkaQ/yPOHZoygHLgJF1AnikpPVW84vYa4hTjTctac20sZt5Av8ezprIo9J0ngOEVCpVn",
	"3op2/5tPPTYTj5xIVXDhAFdhLi5Hum7n9FuHu+dlrWdv4g1qj5suOXqJVNg0gjO0msdmr5U1hYl9nV6g",
	"SjTNUz/4IbzRFptNrZLdr1HoqxsLST8qrwoR3qMO3Zq1rrRlS40qlm4vb/8dAAD//4DgD7LXFwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
