// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ForecastEntry Ein stündlicher Vorhersage-Datenpunkt.
type ForecastEntry struct {
	ForecastFor   time.Time `json:"forecastFor"`
	Precipitation *float32  `json:"precipitation,omitempty"`

	// RunAt Zeitpunkt des Forecast-Runs (alle Einträge eines Calls teilen dasselbe runAt).
	RunAt         time.Time `json:"runAt"`
	Temperature   *float32  `json:"temperature,omitempty"`
	WindDirection *int      `json:"windDirection,omitempty"`
	WindSpeed     *float32  `json:"windSpeed,omitempty"`
}

// Location defines model for Location.
type Location struct {
	// Country ISO 3166-1 alpha-2
	Country   string  `json:"country"`
	Id        int64   `json:"id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Name      string  `json:"name"`

	// Slug URL-safe key, z.B. "potsdam"
	Slug string `json:"slug"`

	// Source Datenquelle, z.B. "open-meteo"
	Source string `json:"source"`

	// Timezone IANA timezone, z.B. Europe/Berlin
	Timezone string `json:"timezone"`
}

// LocationDetail defines model for LocationDetail.
type LocationDetail struct {
	Attribution string `json:"attribution"`

	// Current Eine Messung (current oder historisch).
	Current *Observation `json:"current,omitempty"`

	// Forecast Stündliche Forecast-Einträge für die nächsten 24 h (kann leer sein).
	Forecast []ForecastEntry `json:"forecast"`
	Location Location        `json:"location"`
}

// Observation Eine Messung (current oder historisch).
type Observation struct {
	FetchedAt  time.Time `json:"fetchedAt"`
	ObservedAt time.Time `json:"observedAt"`

	// Precipitation Niederschlag in mm. Fehlt, wenn Quelle null liefert.
	Precipitation *float32 `json:"precipitation,omitempty"`
	Source        string   `json:"source"`

	// Temperature Temperatur in °C (2 m über Grund). Fehlt, wenn Quelle null liefert.
	Temperature *float32 `json:"temperature,omitempty"`

	// WindDirection Windrichtung in Grad (0 = N, 90 = O). Fehlt, wenn Quelle null liefert.
	WindDirection *int `json:"windDirection,omitempty"`

	// WindSpeed Windgeschwindigkeit in km/h (10 m über Grund). Fehlt, wenn Quelle null liefert.
	WindSpeed *float32 `json:"windSpeed,omitempty"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	Message string `json:"message"`
	TraceId string `json:"traceId"`
}

// Problem Problem details object as per RFC 7807.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	TraceId  *string `json:"traceId,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// NotFound Problem details object as per RFC 7807.
type NotFound = Problem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all active locations
	// (GET /api/v1/locations)
	ListLocations(w http.ResponseWriter, r *http.Request)
	// Get location with latest observation and 24h-forecast
	// (GET /api/v1/locations/{slug})
	GetLocationDetail(w http.ResponseWriter, r *http.Request, slug string)
	// Connectivity check
	// (GET /api/v1/ping)
	Ping(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all active locations
// (GET /api/v1/locations)
func (_ Unimplemented) ListLocations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get location with latest observation and 24h-forecast
// (GET /api/v1/locations/{slug})
func (_ Unimplemented) GetLocationDetail(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Connectivity check
// (GET /api/v1/ping)
func (_ Unimplemented) Ping(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListLocations operation middleware
func (siw *ServerInterfaceWrapper) ListLocations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLocations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocationDetail operation middleware
func (siw *ServerInterfaceWrapper) GetLocationDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocationDetail(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/locations", wrapper.ListLocations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/locations/{slug}", wrapper.GetLocationDetail)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ping", wrapper.Ping)
	})

	return r
}

type NotFoundApplicationProblemPlusJSONResponse Problem

type ListLocationsRequestObject struct {
}

type ListLocationsResponseObject interface {
	VisitListLocationsResponse(w http.ResponseWriter) error
}

type ListLocations200JSONResponse struct {
	Attribution string     `json:"attribution"`
	Results     []Location `json:"results"`
}

func (response ListLocations200JSONResponse) VisitListLocationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLocationDetailRequestObject struct {
	Slug string `json:"slug"`
}

type GetLocationDetailResponseObject interface {
	VisitGetLocationDetailResponse(w http.ResponseWriter) error
}

type GetLocationDetail200JSONResponse LocationDetail

func (response GetLocationDetail200JSONResponse) VisitGetLocationDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLocationDetail404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetLocationDetail404ApplicationProblemPlusJSONResponse) VisitGetLocationDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

type Ping200JSONResponse PingResponse

func (response Ping200JSONResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all active locations
	// (GET /api/v1/locations)
	ListLocations(ctx context.Context, request ListLocationsRequestObject) (ListLocationsResponseObject, error)
	// Get location with latest observation and 24h-forecast
	// (GET /api/v1/locations/{slug})
	GetLocationDetail(ctx context.Context, request GetLocationDetailRequestObject) (GetLocationDetailResponseObject, error)
	// Connectivity check
	// (GET /api/v1/ping)
	Ping(ctx context.Context, request PingRequestObject) (PingResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListLocations operation middleware
func (sh *strictHandler) ListLocations(w http.ResponseWriter, r *http.Request) {
	var request ListLocationsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLocations(ctx, request.(ListLocationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLocations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLocationsResponseObject); ok {
		if err := validResponse.VisitListLocationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLocationDetail operation middleware
func (sh *strictHandler) GetLocationDetail(w http.ResponseWriter, r *http.Request, slug string) {
	var request GetLocationDetailRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLocationDetail(ctx, request.(GetLocationDetailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLocationDetail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLocationDetailResponseObject); ok {
		if err := validResponse.VisitGetLocationDetailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Ping operation middleware
func (sh *strictHandler) Ping(w http.ResponseWriter, r *http.Request) {
	var request PingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Ping(ctx, request.(PingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ping")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PingResponseObject); ok {
		if err := validResponse.VisitPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RY2VLcRhT9lVsdPwxlzYYJNlOVB8xmqjAQTOKq2KTcI92R2tPqlruvwJiav/EH5AP8",
	"FH4s1ZJGy0gsdpInpFHf7dztNDfM13GiFSqybHLDDNpEK4vZy7GmfZ2qwD37WhEqco88SaTwOQmthonR",
	"U4nx049WK/fN+hHG3D09MThjE/bTsDIwzL/a4WkuxRaLhccCtL4RiVPHJuwMrU6Nj6A0wSyz7g4Vkk7x",
	"vjboc0t7isy1+6GpYE8osHT7TQVS+BEa+F2bCI3lIfZ3OaFKUjWnAfNYYnSChkQe7KxQu69N8RpzYhMW",
	"cMI+iRiZx+g6QTZhloxQIVs4FeiLRBDPjd8sT6g0nqJxJ0yqtqnt5R8oKHMEArSwDKl/lioLPS4lwp5Q",
	"ZG6/hggoFFrY4VJaIBQSFQTcWpRThEz9movmcQ4TxgkaTqnBTnevhAp2hUF/GVDMP4s4jdnk2ebIY7FQ",
	"+duo1C0UYVgJv0kQgw7VDgr8lArjvr5roL0E6aLUqacf0Sen8kj7JbbNfPk67S6Awzcn8Gy8udkfA5dJ",
	"xPvrzHNhHKEKKWKT9SyM2lsLJBE0KkAo2txgXQFLToLSAJsFo9OpxNxmDtZWHbn+VoVdhbvUKnyMqvGL",
	"hq7staVM8bie3SowK9OwDdhvZ0d9y2cIc7z24Mvg5QDes0STDXj8nrlG4URo3NE/3/H+l1F/q3/x9ElX",
	"eeW92zaRNd6nFKXE0oJOUPVjJNSZkXapihi/aNWh7XD7eBuWnwt9e6mrjuFLNFKotrqV8hMBK9Ao0PLK",
	"eqpltZ6Wmj9lmPcV7C4SF7JdtpzIiGm6Mi+qqP3UmGLO3jdBT6YWzWXeGguvbKc2Vm+qUViNmWq2zG6/",
	"GQgEgrr96keWUMH6BkTQm3OlQCIasChUNmEEYWwfcqw5nRclQtwYfp1XetXR9ykqO381d6WCWtheA9eu",
	"vNQB69oZCK/R2lSF0CtSADpAA5GwpI2wfrTWsTOQ/AiDfMA/bgDrzI/vk2ltmab3xwIDNNaPJA9BKIjj",
	"AexjJMmDK1QKfs36DlQqJUiBMzTZ+muNjap5H1obTfvn5Udn/e+/dqC3DjHcfpuigQOTqmDtxxxqLaOm",
	"3bdCBUb4EbmsCQUHhgfQG8EvcOzBlvt78jjDP7zj2v6EaP3InRHhHAU5t+bxMILeePQfQLLSCbVaKrPn",
	"1Yqyqw9OhQrPCpLXnk4xWkeU3CN+5nEinXCiVdg5oA338TDoKJgVP5daK5FOzwpS2MK1+ABBNlIt5CLA",
	"LSRo4Gx/B56/GD0fvFet/gzKIdze8coSV3eUuyVOqW3Qn5+3tmqlMR51FgcJknc00J1YLfU4b2c8lW4a",
	"8KlOaTKVXM3rzC414sHNlrtQhtAGepEFP9NLUs/9bBLlnIFdaSODK+QUoVF4ZZnHUiPZhEVEiZ0Mh6sH",
	"Br6OWYvFvzo/P4Xt08N8v3TJDGA7Y7kqyGgwQqoIDXwY8kQML8fDD3k+pfCxqNTCw/OXuzWoWw47q8xj",
	"l2hs7spoMB6MssmboOKJYBP2LPsp4zVRluWl0eVqyX4MMQNGZ7NNaOWyx46EpaPylNe8L62PRvdcldpX",
	"pO9jBgZtKvNb2qM2cbVAV5fwSsksFT+0RNuXNYcG6Blwn8QlQgVfdmVL45g7gp4f41K2z3mMeGjrW92y",
	"CyfcysjwxtG1xZ2JOUBaoV4uv4Y7gmmchRsmnMsu50vSN1lSwAoNMil6tRTV7g1Zz9duDuPHE+PFxb+s",
	"lMfkuQi7K03FiWKCQiwIliQnVQGUNGrhsY3Rxl0GywiG5T8Gmnk+QCpzC1eCIpCc0JVIRb6AqwDWN6J+",
	"jbu1a8BjRUs3qyFxaN5VAW6zsf8R58bm7EA5W5NNQHa0Uo69XAq6Bj9Cf16L1l5bwtgF6GTcIi/qtJ08",
	"CQFeotRJ7KKoj+TJ0GEzcMjJSGcp7FifQeoXjLk5zJ1o90C/KP1sXSgyt/vV4O69Qi4p8uA1khG+Xau1",
	"Vx5i26cD1KHhSeR4NcKJIayEalOkJfcWXcM5sqygx+eUs6a3aLIFEtT+16NqbixraXGx+CcAAP//Q//s",
	"xvASAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
