// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: forecasts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getForecastNext24h = `-- name: GetForecastNext24h :many
SELECT f.forecast_for, f.temperature, f.precipitation, f.wind_speed,
       f.wind_direction, f.run_at
FROM forecasts f
WHERE f.location_id = $1
  AND f.forecast_for > NOW()
  AND f.forecast_for <= NOW() + INTERVAL '24 hours'
  AND f.run_at = (SELECT MAX(f2.run_at)
                  FROM forecasts f2
                  WHERE f2.location_id = $1)
ORDER BY f.forecast_for
`

type GetForecastNext24hRow struct {
	ForecastFor   pgtype.Timestamptz `json:"forecast_for"`
	Temperature   pgtype.Float8      `json:"temperature"`
	Precipitation pgtype.Float8      `json:"precipitation"`
	WindSpeed     pgtype.Float8      `json:"wind_speed"`
	WindDirection pgtype.Int4        `json:"wind_direction"`
	RunAt         pgtype.Timestamptz `json:"run_at"`
}

func (q *Queries) GetForecastNext24h(ctx context.Context, locationID int64) ([]GetForecastNext24hRow, error) {
	rows, err := q.db.Query(ctx, getForecastNext24h, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetForecastNext24hRow
	for rows.Next() {
		var i GetForecastNext24hRow
		if err := rows.Scan(
			&i.ForecastFor,
			&i.Temperature,
			&i.Precipitation,
			&i.WindSpeed,
			&i.WindDirection,
			&i.RunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
