// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: locations.sql

package db

import (
	"context"
)

const getLocationBySlug = `-- name: GetLocationBySlug :one
SELECT id, slug, name, country, latitude, longitude, timezone, source
FROM locations
WHERE slug = $1 AND active = TRUE
`

type GetLocationBySlugRow struct {
	ID        int64   `json:"id"`
	Slug      string  `json:"slug"`
	Name      string  `json:"name"`
	Country   string  `json:"country"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Timezone  string  `json:"timezone"`
	Source    string  `json:"source"`
}

func (q *Queries) GetLocationBySlug(ctx context.Context, slug string) (GetLocationBySlugRow, error) {
	row := q.db.QueryRow(ctx, getLocationBySlug, slug)
	var i GetLocationBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.Source,
	)
	return i, err
}

const listActiveLocations = `-- name: ListActiveLocations :many
SELECT id, slug, name, country, latitude, longitude, timezone, source
FROM locations
WHERE active = TRUE
ORDER BY name
`

type ListActiveLocationsRow struct {
	ID        int64   `json:"id"`
	Slug      string  `json:"slug"`
	Name      string  `json:"name"`
	Country   string  `json:"country"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	Timezone  string  `json:"timezone"`
	Source    string  `json:"source"`
}

func (q *Queries) ListActiveLocations(ctx context.Context) ([]ListActiveLocationsRow, error) {
	rows, err := q.db.Query(ctx, listActiveLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveLocationsRow
	for rows.Next() {
		var i ListActiveLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Country,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
