// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Forecast struct {
	LocationID    int64              `json:"location_id"`
	ForecastFor   pgtype.Timestamptz `json:"forecast_for"`
	RunAt         pgtype.Timestamptz `json:"run_at"`
	Temperature   pgtype.Float8      `json:"temperature"`
	Precipitation pgtype.Float8      `json:"precipitation"`
	WindSpeed     pgtype.Float8      `json:"wind_speed"`
	WindDirection pgtype.Int4        `json:"wind_direction"`
	Source        string             `json:"source"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}

type Location struct {
	ID        int64              `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Country   string             `json:"country"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	Timezone  string             `json:"timezone"`
	Source    string             `json:"source"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Observation struct {
	LocationID    int64              `json:"location_id"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	Temperature   pgtype.Float8      `json:"temperature"`
	Precipitation pgtype.Float8      `json:"precipitation"`
	WindSpeed     pgtype.Float8      `json:"wind_speed"`
	WindDirection pgtype.Int4        `json:"wind_direction"`
	Source        string             `json:"source"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}
