// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: observations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestObservation = `-- name: GetLatestObservation :one
SELECT observed_at, temperature, precipitation, wind_speed, wind_direction,
       pressure, humidity, source, fetched_at
FROM observations
WHERE location_id = $1
ORDER BY observed_at DESC
LIMIT 1
`

type GetLatestObservationRow struct {
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	Temperature   pgtype.Float8      `json:"temperature"`
	Precipitation pgtype.Float8      `json:"precipitation"`
	WindSpeed     pgtype.Float8      `json:"wind_speed"`
	WindDirection pgtype.Int4        `json:"wind_direction"`
	Pressure      pgtype.Float8      `json:"pressure"`
	Humidity      pgtype.Float8      `json:"humidity"`
	Source        string             `json:"source"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) GetLatestObservation(ctx context.Context, locationID int64) (GetLatestObservationRow, error) {
	row := q.db.QueryRow(ctx, getLatestObservation, locationID)
	var i GetLatestObservationRow
	err := row.Scan(
		&i.ObservedAt,
		&i.Temperature,
		&i.Precipitation,
		&i.WindSpeed,
		&i.WindDirection,
		&i.Pressure,
		&i.Humidity,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}

const getLatestObservationBySource = `-- name: GetLatestObservationBySource :one
SELECT observed_at, temperature, precipitation, wind_speed, wind_direction,
       pressure, humidity, source, fetched_at
FROM observations
WHERE location_id = $1 AND source = $2
ORDER BY observed_at DESC
LIMIT 1
`

type GetLatestObservationBySourceParams struct {
	LocationID int64  `json:"location_id"`
	Source     string `json:"source"`
}

type GetLatestObservationBySourceRow struct {
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	Temperature   pgtype.Float8      `json:"temperature"`
	Precipitation pgtype.Float8      `json:"precipitation"`
	WindSpeed     pgtype.Float8      `json:"wind_speed"`
	WindDirection pgtype.Int4        `json:"wind_direction"`
	Pressure      pgtype.Float8      `json:"pressure"`
	Humidity      pgtype.Float8      `json:"humidity"`
	Source        string             `json:"source"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) GetLatestObservationBySource(ctx context.Context, arg GetLatestObservationBySourceParams) (GetLatestObservationBySourceRow, error) {
	row := q.db.QueryRow(ctx, getLatestObservationBySource, arg.LocationID, arg.Source)
	var i GetLatestObservationBySourceRow
	err := row.Scan(
		&i.ObservedAt,
		&i.Temperature,
		&i.Precipitation,
		&i.WindSpeed,
		&i.WindDirection,
		&i.Pressure,
		&i.Humidity,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}
