// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetForecastNext24h(ctx context.Context, locationID int64) ([]GetForecastNext24hRow, error)
	GetLatestObservation(ctx context.Context, locationID int64) (GetLatestObservationRow, error)
	GetLocationBySlug(ctx context.Context, slug string) (GetLocationBySlugRow, error)
	ListActiveLocations(ctx context.Context) ([]ListActiveLocationsRow, error)
}

var _ Querier = (*Queries)(nil)
