/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connectivity check */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all active locations */
        get: operations["listLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get location with latest observation and 24h-forecast */
        get: operations["getLocationDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PingResponse: {
            /** @example pong */
            message: string;
            traceId: string;
        };
        Location: {
            /** Format: int64 */
            id: number;
            /** @description URL-safe key, z.B. "potsdam" */
            slug: string;
            name: string;
            /** @description ISO 3166-1 alpha-2 */
            country: string;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            /** @description IANA timezone, z.B. Europe/Berlin */
            timezone: string;
            /** @description Datenquelle, z.B. "open-meteo" */
            source: string;
        };
        /** @description Eine Messung (current oder historisch). */
        Observation: {
            /** Format: date-time */
            observedAt: string;
            /** @description Temperatur in °C (2 m über Grund). Fehlt, wenn Quelle null liefert. */
            temperature?: number;
            /** @description Niederschlag in mm. Fehlt, wenn Quelle null liefert. */
            precipitation?: number;
            /** @description Windgeschwindigkeit in km/h (10 m über Grund). Fehlt, wenn Quelle null liefert. */
            windSpeed?: number;
            /** @description Windrichtung in Grad (0 = N, 90 = O). Fehlt, wenn Quelle null liefert. */
            windDirection?: number;
            source: string;
            /** Format: date-time */
            fetchedAt: string;
        };
        /** @description Ein stündlicher Vorhersage-Datenpunkt. */
        ForecastEntry: {
            /** Format: date-time */
            forecastFor: string;
            temperature?: number;
            precipitation?: number;
            windSpeed?: number;
            windDirection?: number;
            /**
             * Format: date-time
             * @description Zeitpunkt des Forecast-Runs (alle Einträge eines Calls teilen dasselbe runAt).
             */
            runAt: string;
        };
        LocationDetail: {
            location: components["schemas"]["Location"];
            /** @description Letzte Messung. Fehlt, wenn noch keine Beobachtung vorliegt. */
            current?: components["schemas"]["Observation"];
            /** @description Stündliche Forecast-Einträge für die nächsten 24 h (kann leer sein). */
            forecast: components["schemas"]["ForecastEntry"][];
            attribution: string;
        };
        /** @description Problem details object as per RFC 7807.
         *      */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            traceId?: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description pong */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: components["schemas"]["Location"][];
                        attribution: string;
                    };
                };
            };
        };
    };
    getLocationDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location detail mit current und forecast */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
